[package]
name = "mesh-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
common = { path = "../common" }
anyhow.workspace = true
thiserror.workspace = true

# Mesh processing
stl_io.workspace = true
nalgebra.workspace = true
tobj.workspace = true
ply-rs.workspace = true
ahash.workspace = true

